/*
 * LED_Driver.h
 *
 *  Created on: 2021年7月21日
 *      Author: SHEN Zhong
 */

#ifndef INC_LED_DRIVER_H_
#define INC_LED_DRIVER_H_
#ifdef __cplusplus
extern "C" {
#endif

#include "main.h"

int LED_Driver_Setup();
void LED_Driver_SetPWM_One(uint16_t channel, uint8_t dutyCycle);
void LED_Driver_SetPWM_Multi(uint8_t startChannel, uint8_t numofChannels, uint8_t dutyCycle);

#define LED_DRIVER_ADDR							((0x28UL)<<1)

#define DEVICE_CONFIG0_ADDR 					(0x0UL)
#define DEVICE_CONFIG1_ADDR						(0x1UL)
#define LED_CONFIG0_ADDR						(0x2UL)
#define BANK_BRIGHTNESS_ADDR					(0x3UL)
#define BANK_A_COLOR_ADDR						(0x4UL)
#define BANK_B_COLOR_ADDR						(0x5UL)
#define BANK_C_COLOR_ADDR						(0x6UL)
#define LED0_BRIGHTNESS_ADDR					(0x7UL)
#define LED1_BRIGHTNESS_ADDR					(0x8UL)
#define LED2_BRIGHTNESS_ADDR					(0x9UL)
#define LED3_BRIGHTNESS_ADDR					(0xAUL)
#define LED4_BRIGHTNESS_ADDR					(0xBUL)
#define LED5_BRIGHTNESS_ADDR					(0xCUL)
#define LED6_BRIGHTNESS_ADDR					(0xDUL)
#define LED7_BRIGHTNESS_ADDR					(0xEUL)
#define OUT0_COLOR_ADDR							(0xFUL)
#define OUT1_COLOR_ADDR							(0x10UL)
#define OUT2_COLOR_ADDR							(0x11UL)
#define OUT3_COLOR_ADDR							(0x12UL)
#define OUT4_COLOR_ADDR							(0x13UL)
#define OUT5_COLOR_ADDR							(0x14UL)
#define OUT6_COLOR_ADDR							(0x15UL)
#define OUT7_COLOR_ADDR							(0x16UL)
#define OUT8_COLOR_ADDR							(0x17UL)
#define OUT9_COLOR_ADDR							(0x18UL)
#define OUT10_COLOR_ADDR						(0x19UL)
#define OUT11_COLOR_ADDR						(0x1AUL)
#define OUT12_COLOR_ADDR						(0x1BUL)
#define OUT13_COLOR_ADDR						(0x1CUL)
#define OUT14_COLOR_ADDR						(0x1DUL)
#define OUT15_COLOR_ADDR						(0x1EUL)
#define OUT16_COLOR_ADDR						(0x1FUL)
#define OUT17_COLOR_ADDR						(0x20UL)
#define OUT18_COLOR_ADDR						(0x21UL)
#define OUT19_COLOR_ADDR						(0x22UL)
#define OUT20_COLOR_ADDR						(0x23UL)
#define OUT21_COLOR_ADDR						(0x24UL)
#define OUT22_COLOR_ADDR						(0x25UL)
#define OUT23_COLOR_ADDR						(0x26UL)
#define RESET_ADDR								(0x27UL)

#define DEVICE_CONFIG0_CHIP_EN_POS				(6U)
#define DEVICE_CONFIG0_CHIP_EN					(0x1UL << DEVICE_CONFIG0_CHIP_EN_POS)
#define DEVICE_CONFIG1_LOG_SCALE_EN_POS			(5U)
#define DEVICE_CONFIG1_LOG_SCALE_EN				(0x1UL << DEVICE_CONFIG1_LOG_SCALE_EN_POS)
#define DEVICE_CONFIG1_POWER_SAVE_EN_POS		(4U)
#define DEVICE_CONFIG1_POWER_SAVE_EN			(0x1UL << DEVICE_CONFIG1_POWER_SAVE_EN_POS)
#define DEVICE_CONFIG1_AUTO_INCR_EN_POS			(3U)
#define DEVICE_CONFIG1_AUTO_INCR_EN				(0x1UL << DEVICE_CONFIG1_AUTO_INCR_EN_POS)
#define DEVICE_CONFIG1_PWM_DITHERING_EN_POS		(2U)
#define DEVICE_CONFIG1_PWM_DITHERING_EN			(0x1UL << DEVICE_CONFIG1_PWM_DITHERING_EN_POS)
#define DEVICE_CONFIG1_MAX_CURRENT_OPTION_POS	(1U)
#define DEVICE_CONFIG1_MAX_CURRENT_OPTION		(0x1UL << DEVICE_CONFIG1_MAX_CURRENT_OPTION_POS)
#define DEVICE_CONFIG1_LED_GLOBAL_OFF_POS		(0U)
#define DEVICE_CONFIG1_LED_GLOBAL_OFF			(0X1UL << DEVICE_CONFIG1_LED_GLOBAL_OFF_POS)
#define LED_CONFIG0_LED7_BANK_EN_POS			(7U)
#define LED_CONFIG0_LED7_BANK_EN				(0x1UL << LED_CONFIG0_LED7_BANK_EN_POS)
#define LED_CONFIG0_LED6_BANK_EN_POS			(6U)
#define LED_CONFIG0_LED6_BANK_EN				(0x1UL << LED_CONFIG0_LED7_BANK_EN_POS)
#define LED_CONFIG0_LED5_BANK_EN_POS			(5U)
#define LED_CONFIG0_LED5_BANK_EN				(0x1UL << LED_CONFIG0_LED7_BANK_EN_POS)
#define LED_CONFIG0_LED4_BANK_EN_POS			(4U)
#define LED_CONFIG0_LED4_BANK_EN				(0x1UL << LED_CONFIG0_LED7_BANK_EN_POS)
#define LED_CONFIG0_LED3_BANK_EN_POS			(3U)
#define LED_CONFIG0_LED3_BANK_EN				(0x1UL << LED_CONFIG0_LED7_BANK_EN_POS)
#define LED_CONFIG0_LED2_BANK_EN_POS			(2U)
#define LED_CONFIG0_LED2_BANK_EN				(0x1UL << LED_CONFIG0_LED7_BANK_EN_POS)
#define LED_CONFIG0_LED1_BANK_EN_POS			(1U)
#define LED_CONFIG0_LED1_BANK_EN				(0x1UL << LED_CONFIG0_LED7_BANK_EN_POS)
#define LED_CONFIG0_LED0_BANK_EN_POS			(0U)
#define LED_CONFIG0_LED0_BANK_EN				(0x1UL << LED_CONFIG0_LED7_BANK_EN_POS)
#define RESET									(0xFFUL)

#ifdef __cplusplus
}
#endif

#endif /* INC_LED_DRIVER_H_ */
